### ISSUE TITLE
my result is wrong, can you help me?

### ISSUE THREAD

**Issue by mysterywell** [BIGBALLON/cifar-10-cnn#1]
I just follow your code to do,but my model is not correct,why?
have any where i want to do or ?

i use your retrain.h5 to prediction like this:

model = VGG19(weights=None)
filepath1 = os.path.abspath('retrain.h5')
model.load_weights(filepath=filepath1, by_name=True)

this is my result:
Please input picture file to predict ( input Q to exit ):  test_pic/tiger.jpeg
Predicted: [('n04200800', 'shoe_shop', 0.0059397803), ('n04462240', 'toyshop', 0.0048586507), ('n02640242', 'sturgeon', 0.0048460886), ('n12985857', 'coral_fungus', 0.0044603818), ('n03063689', 'coffeepot', 0.0042976518)]

i don't know why...

**Comment by BIGBALLON** [comment]
Oh..
My retrain.h5 is VGG19 for cifar10. but the file "Vgg_prediction.py" is VGG19 for imagenet

so you can't modify `model = VGG19(weights='imagenet')`  
Just use keras' pre_trained weights.
