### ISSUE TITLE
Could I output specified layer using the model defined in 4_Residual_Network/ResNet_keras.py?

### ISSUE THREAD

**Issue by 978326187** [BIGBALLON/cifar-10-cnn#10]
rt

**Comment by BIGBALLON** [comment]
hi, @978326187 
You can check Keras Document for more details.

[How can I obtain the output of an intermediate layer?](https://keras.io/getting-started/faq/#how-can-i-obtain-the-output-of-an-intermediate-layer)

or

[如何获取中间层的输出？
](https://keras.io/zh/getting-started/faq/#how-can-i-obtain-the-output-of-an-intermediate-layer)

**Comment by 978326187** [comment]
好的，谢谢
