### ISSUE TITLE
Would you mind uploading pre-trained models?

### ISSUE THREAD

**Issue by GrayXu** [BIGBALLON/cifar-10-cnn#14]

**Comment by BIGBALLON** [comment]
@GrayXu 

Thanks for your interest.

I have no access to log in  the server my models saved on.
which means I can't  get the models.

However,  there is a repo : 
https://github.com/BIGBALLON/ResNet_CIFAR 
which support some pre-trained models
(https://github.com/BIGBALLON/pretrained_models)
check it if you want.

**Comment by GrayXu** [comment]
thx!
