### ISSUE TITLE
wrong num of parameters in readme 

### ISSUE THREAD

**Issue by wangruohui** [BIGBALLON/cifar-10-cnn#18]
I found that both resent-20 and 110 have the same number of parameters 0.27M. Is there something wrong with that?

Residual-Network20 | GTX1080TI | 0.27M | 128 | 200 | 44 min | 91.82
Residual-Network32 | GTX1080TI | 0.47M | 128 | 200 | 1 h 7 min | 92.68
Residual-Network50 | GTX1080TI | 1.7M | 128 | 200 | 1 h 42 min | 93.18
Residual-Network110 | GTX1080TI | 0.27M | 128 | 200 | 3 h 38 min | 93.93

**Comment by BIGBALLON** [comment]
@wangruohui thanks for your advice, that's a typo.
See https://github.com/BIGBALLON/cifar-10-cnn/commit/6f3dc0e680e7eb69625f830844040b1c5b87135d
