### ISSUE TITLE
Something wrong in the SENET

### ISSUE THREAD

**Issue by ostoe** [BIGBALLON/cifar-10-cnn#5]
There are someting wrong happened in the SENET when I copy the code and train it in my cpu. In the first Epoch 1/250, the begaining the loss is decrease and the accurancy increaing, yet, when the iterations came to 464/781, **the loss became to "nan'**, I don't know what happened.
the config:
cardinality = 4
batch_size = 64 
iterations = 781

Please help me.

**Comment by BIGBALLON** [comment]
I just test it with GPU and it works for me.
Can you try it again or describe some details for me?
