### ISSUE TITLE
import missing in Network_in_Network

### ISSUE THREAD

**Issue by p208p2002** [BIGBALLON/cifar-10-cnn#8]
I found that code **Network_in_Network_bn_keras.py** and **Network_in_Network_keras.py** both missing import with `from keras import backend as K`

**Comment by BIGBALLON** [comment]
Hello, @p208p2002 
Sorry for  for my carelessness , 
I have pushed a new commit to fix it.
And thank you for reminding me. 😸

**Comment by p208p2002** [comment]
@BIGBALLON  You’re welcome :D
